# Generated by Django 5.0.6 on 2024-06-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
